"use client";
import "./globals.css";
import NextAuthProvider from './providers/NextAuth'

// import type { Metadata } from "next";
import { Noto_Sans_JP } from 'next/font/google'
import { HEAD } from '../data/AppData'
import Header from "./components/Header";
import Footer from './components/Footer'

const noto_sans_jp = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['400','700']
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang={HEAD.LOCALE}>
      <head>
        <title>{HEAD.NAME}</title>
        <meta name="description" content={HEAD.DESCRIPTION}/>
      </head>
      <body className={noto_sans_jp.className}>
        <NextAuthProvider>
          <Header />
          {children}
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  );
}
