"use client";
import "./globals.css";
import NextAuthProvider from './providers/NextAuth'
import { css } from "@emotion/react";

// import type { Metadata } from "next";
import { Noto_Sans_JP } from 'next/font/google'
import { HEAD, PROJECT } from '../data/AppData'
import Footer from './components/Footer'
import { vw } from "./utils/Responsive";

const noto_sans_jp = Noto_Sans_JP({
  subsets: ['latin'],
  weight: ['400','700']
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning={true} lang={HEAD.LOCALE}>
      <head>
        <title>{HEAD.NAME}</title>
        <meta name="description" content={HEAD.DESCRIPTION}/>
      </head>
      <body
        className={noto_sans_jp.className}
        css={styles.manageWrapper}
      >
        <NextAuthProvider>
          {children}
          <Footer />
        </NextAuthProvider>
      </body>
    </html>
  );
}

const styles = {
  manageWrapper: css `
    margin: ${vw(140)} auto 0;

    @media (min-width: ${PROJECT.BP}px) {
      margin: 120px auto 0;
    }
  `,
}
